- name: Create directory for nginx
  file:
    path: /etc/nginx
    state: directory
    mode: 0755

- name: Copy NGINX configuration file
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Install load balancer (with NGINX)
  docker_container:
    name: load-balancer
    image: ghcr.io/lakatossz/dce-1-load-balancer:latest
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    state: started
    restart_policy: unless-stopped
    pull: yes
    ports:
    - "80:80"