- name: Install backend (running on python) in Docker container
  docker_container:
    name: backend
    hostname: "{{ inventory_hostname }}"
    image: ghcr.io/lakatossz/dce-1-backend:latest
    state: started
    restart_policy: unless-stopped
    pull: yes
    ports:
    - "5000:5000"